In [1]:
import numpy as np

https://www.freecodecamp.org/news/multi-dimensional-arrays-in-python/

In [5]:
# Create a 2-dimensional array with 3 rows and 4 columns
# pass in a list of lists as an argument
# each inner list represents a row of the array
# and the outer list contains all the rows

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr, arr.shape


(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 (3, 4))

In [3]:
# Modify an element at row 0, column 3
arr[0, 3] = 20
arr

array([[ 1,  2,  3, 20],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
arr2 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]])  # 3 dims
arr2, arr2.shape

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]),
 (1, 3, 4))

Axes are defined for arrays with more than one dimension.  
A 2-dimensional array has two corresponding axes:  
the first running vertically downwards across rows (axis 0),   
and the second running horizontally across columns (axis 1).  


In [21]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])  # calculate the mean of each row
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arrm = np.sum(arr, axis=0)  # there are 4 verticals
arrm

array([15, 18, 21, 24])

In [23]:
arrm2 = np.sum(arr, axis=1)  # there are 3 horizontals
arrm2

array([10, 26, 42])

https://towardsdatascience.com/a-visual-guide-to-multidimensional-numpy-array-aggregation-97a8960b3c59

In [35]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  # 3 dimensional array
c, c.shape

(array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]),
 (2, 2, 2))

In [38]:
s1 = np.sum(c, axis=0)  # axis 0 is the newest added dimension
s1, s1.shape

(array([[ 6,  8],
        [10, 12]]),
 (2, 2))

In [36]:
s2 = np.sum(c, axis=1)  # collapse both 2 dim arrays along the vertical axes
s2, s2.shape

(array([[ 4,  6],
        [12, 14]]),
 (2, 2))

In [37]:
s3 = np.sum(c, axis=2)
s3, s3.shape

(array([[ 3,  7],
        [11, 15]]),
 (2, 2))