In [2]:
#hide
! [ -e /content ] && pip install -Uqq fastbook  
# see if there's a directory called /content (no ,there isn't
# this exist for colab, colab uses pip, and uses an older version of fastai
import fastbook
fastbook.setup_book()

In [3]:
#hide
from fastai.vision.all import *
from fastbook import *

### torch cat - https://pytorch.org/docs/stable/generated/torch.cat.html

In [15]:
x = torch.randn(2, 3)
x

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])

In [40]:
torch.cat((x, x), 0)  # 0 axis is vertical, so it's stacks one over the other

tensor([[-0.3417,  0.3040, -0.6890],
        [-1.1267, -0.2858, -1.0935],
        [-0.3417,  0.3040, -0.6890],
        [-1.1267, -0.2858, -1.0935]])

In [41]:
torch.cat((x, x))  # default as 0

tensor([[-0.3417,  0.3040, -0.6890],
        [-1.1267, -0.2858, -1.0935],
        [-0.3417,  0.3040, -0.6890],
        [-1.1267, -0.2858, -1.0935]])

In [16]:
torch.cat((x, x), 1)  # and 1 as horizontal

tensor([[ 0.3367,  0.1288,  0.2345,  0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863,  0.2303, -1.1229, -0.1863]])

In [17]:
torch.cat((x, x), -1)  # -1 is the same as 1; is the last axis

tensor([[ 0.3367,  0.1288,  0.2345,  0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863,  0.2303, -1.1229, -0.1863]])

### torch view - https://pytorch.org/docs/stable/generated/torch.Tensor.view.html

In [46]:
x = torch.randn(4, 4)
x

tensor([[ 0.2695, -0.2104, -0.7328,  0.1043],
        [ 1.0414, -0.3997, -2.2933,  0.4976],
        [-2.4801, -0.4175, -1.1955,  0.8123],
        [-0.3063, -0.3302, -0.9808,  0.1947]])

In [47]:
x.size()

torch.Size([4, 4])

In [55]:
y = x.view(16)
y

tensor([ 0.2695, -0.2104, -0.7328,  0.1043,  1.0414, -0.3997, -2.2933,  0.4976, -2.4801, -0.4175, -1.1955,  0.8123, -0.3063, -0.3302, -0.9808,  0.1947])

In [51]:
y.size()

torch.Size([16])

In [77]:
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions = fix to 8 columns and rows are 16/8=2
z,z[1],z[-1]

(tensor([[ 0.2695, -0.2104, -0.7328,  0.1043,  1.0414, -0.3997, -2.2933,  0.4976],
         [-2.4801, -0.4175, -1.1955,  0.8123, -0.3063, -0.3302, -0.9808,  0.1947]]),
 tensor([-2.4801, -0.4175, -1.1955,  0.8123, -0.3063, -0.3302, -0.9808,  0.1947]),
 tensor([-2.4801, -0.4175, -1.1955,  0.8123, -0.3063, -0.3302, -0.9808,  0.1947]))

In [76]:
t = y.view(8,2)
t

tensor([[ 0.2695, -0.2104],
        [-0.7328,  0.1043],
        [ 1.0414, -0.3997],
        [-2.2933,  0.4976],
        [-2.4801, -0.4175],
        [-1.1955,  0.8123],
        [-0.3063, -0.3302],
        [-0.9808,  0.1947]])

In [80]:
z.size()

torch.Size([2, 8])

In [91]:
a = torch.randn(1, 2, 3, 4)  # how??
a

tensor([[[[ 0.7694,  2.5574,  0.5716,  1.3596],
          [ 0.4334, -0.7172,  1.0554, -1.4534],
          [ 0.5667, -0.7098, -0.4875,  0.0501]],

         [[ 0.3273,  0.1292,  2.8520, -0.7436],
          [ 0.9478, -0.6766, -0.5730, -0.3303],
          [-0.3071, -0.7155,  0.0762, -0.2127]]]])

In [85]:
a.size()

torch.Size([1, 2, 3, 4])

In [86]:
b = a.transpose(1, 2)  # Swaps 2nd and 3rd dimension
b.size()

torch.Size([1, 3, 2, 4])

In [11]:
c = a.view(1, 3, 2, 4)  # Does not change tensor layout in memory
c.size()

torch.Size([1, 3, 2, 4])

In [12]:
torch.equal(b, c)

False

### torch squeeze - https://pytorch.org/docs/stable/generated/torch.squeeze.html

In [115]:
x = torch.zeros(2, 1, 2, 1, 2)
x, x.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [116]:
y = torch.squeeze(x)
y, y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [118]:
y = torch.squeeze(x, 0)
y, y.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [119]:
y = torch.squeeze(x, 1)
y, y.size()

(tensor([[[[0., 0.]],
 
          [[0., 0.]]],
 
 
         [[[0., 0.]],
 
          [[0., 0.]]]]),
 torch.Size([2, 2, 1, 2]))

In [120]:
y = torch.squeeze(x, (1, 2, 3))
y, y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

### numpy squeeze - https://numpy.org/doc/stable/reference/generated/numpy.squeeze.html

In [2]:
import numpy as np

In [7]:
x = np.array([[0], [1], [2]])  # 1st dimension is 3, and each dimension has 1 element
x, x.shape

(array([[0],
        [1],
        [2]]),
 (3, 1))

In [3]:
x = np.array([[[0], [1], [2]]])
x, x.shape

(array([[[0],
         [1],
         [2]]]),
 (1, 3, 1))

In [37]:
np.squeeze(x), np.squeeze(x).shape

(array([0, 1, 2]), (3,))

In [38]:
np.squeeze(x, axis=0), np.squeeze(x, axis=0).shape

(array([[0],
        [1],
        [2]]),
 (3, 1))

In [11]:
#x = np.array([[[0], [1], [2]]])
np.squeeze(x, axis=1) #, np.squeeze(x, axis=1).shape

array([0, 1, 2])

In [39]:
#x = np.array([[[0], [1], [2]]])
np.squeeze(x, axis=2), x.shape

(array([[0, 1, 2]]), (1, 3, 1))

In [40]:
x = np.array([[1234]])
x.shape

(1, 1)

In [41]:
np.squeeze(x)

array(1234)

In [42]:
np.squeeze(x).shape

()

In [43]:
np.squeeze(x)[()]

1234

### torch unsqueeze - https://pytorch.org/docs/stable/generated/torch.unsqueeze.html
Returns a new tensor with a dimension of size one inserted at the specified position.



In [22]:
x= torch.tensor([1, 2, 3, 4])
x, x.shape

(tensor([1, 2, 3, 4]), torch.Size([4]))

In [25]:
torch.unsqueeze(x, 0), x.size(), x.shape  # from 4 elements to 1 element at dimension 0
# dim 0 is the vertical and it has the size 1, just like the original

(tensor([[1, 2, 3, 4]]), torch.Size([4]), torch.Size([4]))

In [24]:
torch.unsqueeze(x, 1), x.size()
# dim 1 is the horizontal, and it has a now a size of 1

(tensor([[1],
         [2],
         [3],
         [4]]),
 torch.Size([4]))

https://stackoverflow.com/questions/57237352/what-does-unsqueeze-do-in-pytorch

### torch.where

In [4]:
help(torch.where)

Help on built-in function where in module torch:

where(...)
    where(condition, input, other, *, out=None) -> Tensor
    
    Return a tensor of elements selected from either :attr:`input` or :attr:`other`, depending on :attr:`condition`.
    
    The operation is defined as:
    
    .. math::
        \text{out}_i = \begin{cases}
            \text{input}_i & \text{if } \text{condition}_i \\
            \text{other}_i & \text{otherwise} \\
        \end{cases}
    
    .. note::
        The tensors :attr:`condition`, :attr:`input`, :attr:`other` must be :ref:`broadcastable <broadcasting-semantics>`.
    
    Arguments:
        condition (BoolTensor): When True (nonzero), yield input, otherwise yield other
        input (Tensor or Scalar): value (if :attr:`input` is a scalar) or values selected at indices
                              where :attr:`condition` is ``True``
        other (Tensor or Scalar): value (if :attr:`other` is a scalar) or values selected at indices
                

In [5]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)
x

tensor([[ 0.3367,  0.1288],
        [ 0.2345,  0.2303],
        [-1.1229, -0.1863]])

In [7]:
torch.where(x > 0, 1.0, 0.0)  # if x>0 replace with 1, otherwise replace with 0

tensor([[1., 1.],
        [1., 1.],
        [0., 0.]])

In [9]:
torch.where(x > 0, x, y)  # if x>0 replace with x, otherwise replace with y=1

tensor([[0.3367, 0.1288],
        [0.2345, 0.2303],
        [1.0000, 1.0000]])

In [11]:
x = torch.randn(2, 2, dtype=torch.double)
x

tensor([[ 0.5349,  0.8094],
        [ 1.1103, -1.6898]], dtype=torch.float64)

In [12]:
torch.where(x > 0, x, 0.)  # if x>0 replace with x, otherwise replace with 0

tensor([[0.5349, 0.8094],
        [1.1103, 0.0000]], dtype=torch.float64)

### mnist code

In [16]:
trgts = tensor([1,0,1])
trgts

tensor([1, 0, 1])

In [17]:
prds = tensor([0.9, 0.4, 0.2])
prds

tensor([0.9000, 0.4000, 0.2000])

In [20]:
torch.where(trgts==1, 1-prds, prds)  # if targets equal 1, replace with 1-prds, otherwise replace with prds: 1-0.9, 0.4, 1-0.8

tensor([0.1000, 0.4000, 0.8000])